export const settings = {
  gameMode: "GS++",
  gameType: "FFA",
  isRanked: true,
  isAnonymous: false,
  isCircular: false,
  isScaled: false,
  powerupIds: [1, 9],
  powerupAmounts: {},
  powerupIdsAlways: [],
  powerupFrequency: 1.25,
  powerupRadius: 25,
  firstTo: 30,
  pointsPerSurvive: 1,
  pointsPerKill: 0,
  fps: 60,
  fieldWidth: 922,
  fieldHeight: 763,
  curveSize: 6.3,
  curveTouchiness: 1.64,
  curveSpeed: 180,
  turnRadius: 38.5,
  holeSize: 22.4,
  holeFrequency: 0.57,
  isEraseDead: false,
};
